const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#FF6B2B",
    background: "#0D0D0E",
    foreground: "#FFFFFF",
    card: "#1A1A1B",
    cardForeground: "#FFFFFF",
    primary: "#FF6B2B",
    primaryForeground: "#FFFFFF",
    secondary: "#252526",
    secondaryForeground: "#F0F0F0",
    muted: "#252526",
    mutedForeground: "#8A8A8F",
    accent: "#FF6B2B",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2C",
    input: "#1E1E1F",
    success: "#30D158",
    successForeground: "#FFFFFF",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF6B2B",
    background: "#0D0D0E",
    foreground: "#FFFFFF",
    card: "#1A1A1B",
    cardForeground: "#FFFFFF",
    primary: "#FF6B2B",
    primaryForeground: "#FFFFFF",
    secondary: "#252526",
    secondaryForeground: "#F0F0F0",
    muted: "#252526",
    mutedForeground: "#8A8A8F",
    accent: "#FF6B2B",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2C",
    input: "#1E1E1F",
    success: "#30D158",
    successForeground: "#FFFFFF",
  },
  radius: 14,
};

export default colors;
